services:
  db:
    image: postgres:15
    container_name: moneymap_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=segredo
      - POSTGRES_DB=moneymap_db
    ports:
      - "5432:5432"

volumes:
  postgres_data: